import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "./components/navigation";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Prompt } from "next/font/google";
import Footer from "./components/footer";


const prompt = Prompt({
  subsets: ['thai', 'latin'], // รองรับภาษาไทย
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata = {
  title: "frontend",
  description: "Generated by create next app",
};

export function renderFooter() {
  return <Footer />;
  if (Router.pathname === '/Home') {
    return <Footer type="home" />;
  } else if (Router.pathname === '/about') {
    return <Footer type="about" />;
  } else if (Router.pathname === '/contact') {
    return <Footer type="contact" />;
  } else if (Router.pathname === '/service') {
    return <Footer type="service" />;
  }
}

export function renderNevigation() {
  return <Navigation />;
  if (Router.pathname === '/Home') {
    return <Nevigation type="home" />;
  } else if (Router.pathname === '/about') {
    return <Navigation type="about" />;
  } else if (Router.pathname === '/contact') {
    return <Navigation type="contact" />;
  } else if (Router.pathname === '/service') {
    return <Navigation type="service" />;
  }
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className} style={{ backgroundColor: 'black' }}>
        {renderNevigation()}
        <main style={{ marginTop: '58px' }}>
          {children}
        </main>
       
        {renderFooter()}
      </body>
    </html>
  );
}

