import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className         = {`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        
        <div className    = "container">
          <h1>hello</h1>
        </div>

        <div className    = ".container">
          <h1>hello</h1>
        </div>

        <div className    = ".container-sm">
          <h1>hello</h1>
        </div>

        <div className    = ".container-md">
          <h1>hello</h1>
        </div>

        <div className    = ".container-lg">
          <h1>hello</h1>
        </div>

        <div className    = ".container-xl">
          <h1>hello</h1>
        </div>

        <div className    = ".container-xxl">
          <h1>hello</h1>
        </div>

        <div className    = "container-fluid">
          <h1>hello</h1>
        </div>
        


        
        
        {children}
      </body>
    </html>
  );
}
